resource "aws_db_instance" "mariadb" {
  identifier                 = "${var.identifier}"
  allocated_storage          = "${var.storageamount}"
  storage_type               = "${var.storageType}"
  engine                     = "mariadb"
  instance_class             = "${var.instance_class}"
  name                       = "${var.db_name}"
  username                   = "${var.username}"
  password                   = "${var.password}"
  storage_encrypted          = "true"
  maintenance_window         = "${var.maintenanceWindow}"
  auto_minor_version_upgrade = "${var.autoMinorUpgrade}"
  multi_az                   = "${var.multiAZ}"
  backup_window              = "${var.backupWindow}"
  backup_retention_period    = "${var.backupRetention}"
  kms_key_id                 = "${var.dbkms}"
  db_subnet_group_name       = "${var.dbsnetgroup}"
  skip_final_snapshot        = "${var.skipSnapshot}"
}
